export {default as Home} from './Home'
export {default as Inbox} from './Inbox'
export {default as Explore} from './Explore'
export {default as ViewProfile} from './ViewProfile'
export {default as UploadPost} from './UploadPost'